apiVersion: apps/v1
kind: Deployment
metadata:
  name: bold-rewards-svc-template # This should match the name in base/deployment.yaml
spec:
  template:
    spec:
      containers:
        - name: app # This should match the container name in base/deployment.yaml
          image: placeholder-image # This placeholder will be replaced by the CI/CD pipeline
