# deploy/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment # Имя будет дополнено префиксом в kustomization.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: nestjs-app:latest # Будет заменено в kustomization
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
